# Generated by Django 3.2 on 2021-04-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='serial_number',
        ),
    ]
