# Generated by Django 3.2 on 2021-05-06 08:58

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='items',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
    ]
